### ISSUE TITLE
bullet_list_icon don't show on iOS devices. 7.0.0-alpha

### ISSUE THREAD

**Issue by JavierL1** [iamacup/react-native-markdown-display#122]
I tried 7.0.0-alpha.2 too, but same results. On Android it works as expected
For the bullet_list_icon I'm using this style:
```
bullet_list_icon: {
  ...Platform.select({
    android: {
      fontSize: 25,
      marginTop: 5,
    },
    ios: {
      fontSize: 40,
      marginTop: 9,
    },
    default: {
      fontSize: 40,
      marginTop: 9,
    },
  }),
},
```

- debugPrintTree
```
body
-bullet_list
--list_item
---textgroup
----text
--list_item
---textgroup
----text
--list_item
---textgroup
----text
--list_item
---textgroup
----text
```

- 6.1.6
<img width="385" alt="Screen Shot 2020-10-29 at 10 52 52" src="https://user-images.githubusercontent.com/21026919/97582786-e921ce00-19d4-11eb-9afc-06bdadc2c84c.png">

- 7.0.0-alpha
<img width="397" alt="Screen Shot 2020-10-29 at 10 50 50" src="https://user-images.githubusercontent.com/21026919/97582779-e7f0a100-19d4-11eb-9a4d-632d2ea00f65.png">

- 7.0.0-alpha.2
<img width="424" alt="Screen Shot 2020-10-29 at 10 54 02" src="https://user-images.githubusercontent.com/21026919/97582911-12daf500-19d5-11eb-9a90-9506a9415225.png">

**Comment by somegoodpixels** [comment]
@JavierL1 — were you using a custom font?
* This package renders a middot for ios and a bullet character for all other devices. That middot may be defined in the font — and may be higher or lower on the baseline.
* First, try removing the large font size declaration on the bullet icon. Each list item seems to crop overflowed content, and your font size may be so large that the bullet is pushed beyond the list item boundaries and cropped.
* If you still do not see the icon, try changing the font that's specified for Markdown (just as a test... or using a system default, which is likely to have greater character support).
* This may expose what's causing the issue — either a missing/high font glyph — or the font size.

Since it looks like you're using Open Sans or Noto font, ensure that when exported/downloaded the middot \u00B7 character is part of the font glyph set — and that you haven't exported with any custom subsetting (like "basic latin" or "latin-1") which may remove this character to preserve file size.
