### ISSUE TITLE
Styles from text seem to override styles for Headers

### ISSUE THREAD

**Issue by vladp** [iamacup/react-native-markdown-display#50]
I tested this on both, Android and Web, and behavior seems to be the same.

If I specify a style , say,  `color: 'red'`    for ext, and `color: 'green' for Header 1`,   everything is 'red' (including headers).
Same for fontSize. 

Perhaps, I am mistaken, but I am thinking, that styles for 'text' should not override styles for other sections.

```

  render() {
    console.log('App::render');

    const localStyle={
      text: {color: 'red'}, //text should be red
      heading1: {fontSize:52, color: 'green'},//headings should be green
      
    }
    return (
      <ScrollView>
      <View>
        <Text> Mark Down with react-native-markdown-display </Text>
        <View style={{ flex: 1, margin:5,  borderWidth: 2 }}>
          <Markdown style={localStyle} markdownit={md}>
            {MD_TEST_DATA2}
          </Markdown>
        </View>
      </View>
      </ScrollView>
    );
  }
```

**Comment by iamacup** [comment]
Hey

A couple of things

1) You are mistaken, but its not your fault - the text name leads people to believe it should be used to style text, this is a hangover from the fork of react-native-markdown-renderer and i think i am going to need to do something about it

2) The readme does mention this but maybe its not clear enough - section 'how to style stuff'

The tree for, a header (for example - i have ommitted paragraphs and text groups in this example) is:

 * root
   * heading1
     * text

so, because the style is applied at the top and overwridden at the bottom, by applying styles to text you are saying 'all text rendered (apart from two annoying exceptions with lists) should have this color'

so instead you should apply the global style at the top, and then granular styles further down

I am going to do something about the 'text' class as it is confusing, i might move it up a couple of levels so its either equal with, or higher than, in the example - the heading1 style. not sure yet.

Either way, global styles should apply to root

**Comment by iamacup** [comment]
I also might add a debug property to `<Markdown>` so it prints out the component hierarchy so this is easier to see what styles what

**Comment by vladp** [comment]
Ooh... 
Thank you !, I do not know how why, I missed

https://github.com/iamacup/react-native-markdown-display#How-to-style-stuff

It works well now (as you suggested, I was miss-using the 'text', and for my needs I should have using 'paragraph').


Yes, printing out component hierarchy would be a nice debugging help, not just for styling stuff, but also, potentially for pluging development (one of these days I would like to figure out, if it is even possible,  to do KaTeX with this, but *without* webview).
