### ISSUE TITLE
textAlign doesn't work

### ISSUE THREAD

**Issue by cromatikap** [iamacup/react-native-markdown-display#81]
```
const markdownStyle = StyleSheet.create({
  body: {
    textAlign: 'justify',
    borderWidth: 1,
    borderColor: 'red'
  }
})

...

<Markdown style={markdownStyle}>{termsAndConditions}</Markdown>
```

No problem with the red border, although `textAlign` doesn't make any difference. I tried on other elements like text or heading, heading1 and I have the same behavior.
Any solution to this?

**Comment by iamacup** [comment]
This is because of this: https://github.com/iamacup/react-native-markdown-display/issues/88 which i am going to have a think about fixing in the long term.

In the short term you would need to modify anything in the component tree that renders (see `printDebugTree`) as a nested `<Text>` after a view - most likely sticking the textAlign on the `paragraph` and `textgroup` styles will do the trick for now

**Comment by cromatikap** [comment]
Okay, thank you for the information. I'll wait for the update but it's good to know a temporary alternative
