### ISSUE TITLE
is that possible to  reduce gap between numbered list items?

### ISSUE THREAD

**Issue by vidux** [iamacup/react-native-markdown-display#82]
hi i'm new to react-native-markdown-display  package. i don't know how to reduce gap/ margin between two numbered list items can anyone help? many thanks
![markdownexample](https://user-images.githubusercontent.com/24480091/85739748-b01fd700-b71e-11ea-9a43-2c5e4473dd14.png)

**Comment by iamacup** [comment]
Yes - if you use debugPrintTree you will see what is rendered - you will see that a `paragraph` is rendered as a child of the `list_item` which has margin on top and bottom.

In order to apply specific styles to the `paragraph` for the list items only - you will need to do something like this:

```jsx
import React from 'react';
import { SafeAreaView, ScrollView, StatusBar, Text, StyleSheet, TouchableOpacity, View, Platform } from 'react-native';

import Markdown, {hasParents} from 'react-native-markdown-display';

import textStyleProps from 'react-native-markdown-display/src/lib/data/textStyleProps'

const copy = `
# Header 
1. height
2. length

Something

* Bullet 1
* Bullet 2
`;

const rules = {
  paragraph: (node, children, parent, styles) => (
    <View key={node.key} style={hasParents(parent, 'ordered_list') ? styles._VIEW_SAFE_paragraph_ol_child : styles._VIEW_SAFE_paragraph}>
      {children}
    </View>
  ),
}

const styles = {
  ordered_list_icon: {
    ...Platform.select({
      ios: {
        lineHeight: 0,
      },
      android: {
        lineHeight: 0,
      },
      default: {
        lineHeight: 0,
      },
    }),
  },
  paragraph_ol_child: {
    marginTop: 0,
    marginBottom: 0,
  }
}

const App: () => React$Node = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ScrollView
          contentInsetAdjustmentBehavior="automatic"
          style={{height: '100%'}}
        >
            <Markdown
              debugPrintTree
              rules={rules}
              style={styles}
            >
              {copy}
            </Markdown>
        </ScrollView>
      </SafeAreaView>
    </>
  );
};

export default App;
```

I also changed line height on the `ordered_list_icon`

see https://github.com/iamacup/react-native-markdown-display/blob/master/src/lib/renderRules.js and https://github.com/iamacup/react-native-markdown-display/blob/master/src/lib/styles.js for original settings

![image](https://user-images.githubusercontent.com/12894620/86499649-4473e480-bd84-11ea-8d05-9a40bddd9d28.png)
