### ISSUE TITLE
Touchables and View within Link custom rule not working

### ISSUE THREAD

**Issue by ericlifs** [iamacup/react-native-markdown-display#85]
Hi everyone! I found this library awesome and very useful so thanks for that!

I'm facing an issue when trying to override the default link rule with my custom Link component which basically renders the following:

```
<TouchableOpacity onPress={onLinkPressed}>
   <Text>{props.text}</Text>
</TouchableOpacity>
```

But I am not able to see anything being rendered
![image](https://user-images.githubusercontent.com/7376892/86410790-d4853180-bc91-11ea-98b4-f7deadbbebf1.png) 

I'm overriding the default link rule like this:
`link: (node: any): JSX.Element => <Link key={node.key} href={node.attributes.href} text={node.children[0].content} />,`

I'm sure that `props.text` is defined and it has text content, the same code is working perfectly on the web (using react-native-web). Also, if I change the TouchableOpacity to a View component, it does not work either, the only way I was able to make it work is by just returning the inner `<Text>{props.text}</Text>`.

Thank you very much!

**Comment by iamacup** [comment]
What does this render rule show:

`link: (node: any): JSX.Element => <Text>{node.children[0].content}</Text>,`

**Comment by ericlifs** [comment]
Hi @iamacup !

It does work perfectly as you can see:
![image](https://user-images.githubusercontent.com/7376892/86467728-4dc16a80-bd0c-11ea-81f9-055930caa40a.png)

And it stops working as soon as I place a TouchableOpacity/View wrapping it.

Thanks!

**Comment by iamacup** [comment]
This is real shitter and is related to this: https://github.com/iamacup/react-native-markdown-display/issues/42#issuecomment-562199006

Basically - if you use `printDebugTree` you will see this:

```
body (:VIEW)
-paragraph (:VIEW)
--textgroup (:TEXT)
---link (:TEXT)
----text (:TEXT)
```
So changing the `link` to be `TouchableOpacity` actually renders something like

```jsx
<View>
  <View>
    <Text>
      <TouchableOpacity>
        ...
```
which apparently is not supproted - https://stackoverflow.com/questions/50348514/how-can-i-wrap-a-touchableopacity-around-text-within-text

Really, we need to remove nested <Text><Text> but i don't know what the solution to the problem created by doing that (https://github.com/iamacup/react-native-markdown-display/issues/42#issuecomment-562199006) is - any ideas?

You can change the TextGroup rule to be a View which will fix your problem here, but might create others as mentioned

**Comment by iamacup** [comment]
I have opened a seperate issue about the underlying problem here: https://github.com/iamacup/react-native-markdown-display/issues/88
