### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by aaronwilly** [iamacup/react-native-markdown-display#97]
The package at "node_modules\markdown-it\lib\index.js" attempted to import the Node standard library module "punycode". It failed because the native React runtime does not include the Node standard library. Read more at https://docs.expo.io/introduction/faq/#can-i-use-nodejs-packages-with-expo      
Failed building JavaScript bundle.

**Comment by iamacup** [comment]
I don't test this against Expo so will need some help from you if we are going to fix this, can you work out which of these are introducing the punycode dep? (from package.json)

```
  "dependencies": {
    "css-to-react-native": "^3.0.0",
    "markdown-it": "^10.0.0",
    "prop-types": "^15.7.2",
    "react-native-fit-image": "^1.5.5"
  },
```

**Comment by aaronwilly** [comment]
Thanks. @iamacup  it is working.

**Comment by abirchall** [comment]
FWIW I ran into this as well and simply installed `punycode`. I think the issue is with `markdown-it` based on the following error message:

<img width="416" src="https://user-images.githubusercontent.com/456610/88617729-372cdb80-d04c-11ea-8555-7e77b997afba.png">

I see punycode referenced in a couple places in the project: https://github.com/markdown-it/markdown-it/search?q=punycode&unscoped_q=punycode

... yet I don't see a dependency in the `package.json` https://github.com/markdown-it/markdown-it/blob/master/package.json

**Comment by abirchall** [comment]
here we go... https://github.com/markdown-it/markdown-it/issues/230 raises this issue to `markdown-it` but they don't acknowledge it as valid, stating that this is included by default by `nodejs` / `browserify`

**Comment by ncoen97** [comment]
I quote @kethan1 

> It seems like after punycode is installed with: yarn install punycode, or npm install punycode, or expo install punycode(recommended for expo) it should work

It worked for me!
